/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "main.h"			//Header necesarios
#include <stdlib.h>
#include "TEXT.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_SLIDER_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_0 (GUI_ID_USER + 0x03)
#define ID_TEXT_1 (GUI_ID_USER + 0x04)
#define ID_TEXT_2 (GUI_ID_USER + 0x05)


// USER START (Optionally insert additional defines)
WM_HWIN      hItem;		// Handler
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
int TIME_RED=0;						//
char acText[3] = {0};			//Buffer ASCII
unsigned char *itoa(int dato); //Conversión de entero a ASCII
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "FrameWinMoran", ID_FRAMEWIN_0, 0, 0, 240, 320, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LED ROJO", ID_BUTTON_0, 60, 228, 100, 40, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 50, 150, 140, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "000", ID_TEXT_0, 100, 115, 40, 30, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Dr. José Miguel Morán Loza", ID_TEXT_1, 50, 40, 140, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Tópicos Selectos en Computación", ID_TEXT_2, 40, 16, 160, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  int NCode;
  int Id;
  // USER START (Optionally insert additional variables)
	   GUI_TOUCH_StoreState(-1, 1);			//Permite la selección de widgets
																			//Resaltando su enfoque
  // USER END

  switch (pMsg->MsgId) {
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'LED ROJO'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
						BSP_LED_Toggle(LED4);	//Cambiar estado el Led Rojo tras dar click en el boton	
			  // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			  // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
            hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);		
						TIME_RED=SLIDER_GetValue(hItem);					//Obtener el valor del Slider
																											
																											//Convertirlo a ASCII
						acText[0] = '0'+(TIME_RED / 100);					//Centenas
						acText[1] = '0'+((TIME_RED % 100)/10);		//Decenas
						acText[2] = '0'+((TIME_RED % 100)%10);		//Unidades
			
						hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
						TEXT_SetText(hItem, acText);							//Colocar valor en TexBox

			   // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
	
		/* Este case WM_INIT_DIALOG: se añade para preparar el entorno 
		y configurar las condiciones iniciales de los widgets		l*/		
	case WM_INIT_DIALOG:	
												
		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
	  TEXT_SetFont(hItem,&GUI_Font24_ASCII);
		TEXT_SetText(hItem,"000");
	
		hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
		SLIDER_SetNumTicks(hItem,5);
		SLIDER_SetRange(hItem,0,100);
	
	break;

  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFrameWinMoran
*/
WM_HWIN CreateFrameWinMoran(void);
WM_HWIN CreateFrameWinMoran(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
