/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "main.h"			//Header necesarios
#include <stdlib.h>
#include "TEXT.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0            (GUI_ID_USER + 0x00)
#define ID_TEXT_0            (GUI_ID_USER + 0x01)
#define ID_TEXT_1            (GUI_ID_USER + 0x02)
#define ID_SLIDER_0            (GUI_ID_USER + 0x03)
#define ID_SLIDER_1            (GUI_ID_USER + 0x04)
#define ID_TEXT_2            (GUI_ID_USER + 0x05)
#define ID_TEXT_3            (GUI_ID_USER + 0x06)
#define ID_TEXT_4            (GUI_ID_USER + 0x07)
#define ID_TEXT_5            (GUI_ID_USER + 0x08)
#define ID_TEXT_6            (GUI_ID_USER + 0x0A)
#define ID_TEXT_7            (GUI_ID_USER + 0x0B)
#define ID_TEXT_8            (GUI_ID_USER + 0x0C)
#define ID_TEXT_9            (GUI_ID_USER + 0x0D)
#define ID_TEXT_10            (GUI_ID_USER + 0x0E)


// USER START (Optionally insert additional defines)

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "FrameWinMoran", ID_FRAMEWIN_0, 1, 0, 240, 320, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PROYECTO FINAL", ID_TEXT_0, 27, 17, 196, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Francisco Mora", ID_TEXT_1, 67, 48, 105, 26, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 11, 138, 203, 20, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_1, 12, 204, 204, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Eje Y: (Eje vertical)", ID_TEXT_2, 70, 179, 103, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Eje X: (Eje horizontal)", ID_TEXT_3, 64, 120, 134, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "218318865", ID_TEXT_4, 81, 69, 64, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "-180", ID_TEXT_5, 7, 158, 34, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "-180", ID_TEXT_6, 8, 225, 32, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_7, 111, 152, 21, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "0", ID_TEXT_8, 113, 219, 19, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "180", ID_TEXT_9, 203, 155, 25, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "180", ID_TEXT_10, 201, 219, 28, 20, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	GUI_TOUCH_StoreState(-1, 1);			//Permite la selección de widgets //Resaltando su enfoque

  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'PROYECTO FINAL'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of 'Francisco Mora'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_13H_ASCII);
    // USER START (Optionally insert additional code for further widget initialization)

	// Se fija el rango para el eje X (-180 grados a 180 grados que hacen los 360 grados totales)
    hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0);
	SLIDER_SetRange(hItem, -180, 180);

	// Se fija el rango para el eje Y (-180 grados a 180 grados que hacen los 360 grados totales)
	hItem = WM_GetDialogItem(pMsg->hWin, ID_SLIDER_1);
	SLIDER_SetRange(hItem, -180, 180);

	// Se guarda el manejador en una variable global para ser modificado desde App.c
	hItem_global = pMsg->hWin;

	// Se avisa que ya se inicializo la ventana para ser modificada desde el ciclo de App.c
	seInicializoLaVentana = 1;
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_1: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)

  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFrameWinMoran
*/
WM_HWIN CreateFrameWinMoran(void);
WM_HWIN CreateFrameWinMoran(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
